version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    groups: {github-actions: {patterns: ['*']}}
    schedule: {interval: weekly}
    cooldown:
      default-days: 3
    assignees:
      - ToshY

  - package-ecosystem: "composer"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "weekly"
      day: "sunday"
    assignees:
      - ToshY