repos:
  - repo: local
    hooks:
      - id: phpcsfixer
        name: PHP-CS-Fixer
        language: system
        files: \.php$
        entry: docker compose run -T --rm php vendor/bin/php-cs-fixer fix --dry-run -v --diff --path-mode=intersection --config=.php-cs-fixer.dist.php --show-progress=none
      - id: phpstan
        name: PHPStan
        language: system
        files: \.php$
        pass_filenames: false
        entry: docker compose run -T --rm php vendor/bin/phpstan analyse --memory-limit 1G --error-format=table
      - id: phpmd
        name: PHPMD
        language: system
        files: \.php$
        pass_filenames: false
        entry: docker compose run -T --rm php vendor/bin/phpmd src/ text phpmd.xml
      - id: phpunit
        name: PHPUnit
        language: system
        files: \.php$
        pass_filenames: false
        entry: docker compose run -T --rm php vendor/bin/phpunit
