site_name: BunnyNet-PHP
site_description: bunny.net API client for PHP
repo_name: ToshY/BunnyNet-PHP
repo_url: https://github.com/ToshY/BunnyNet-PHP
docs_dir: docs/
site_dir: site/
theme:
  name: material
  font: false
  logo: images/favicon.png
  favicon: images/favicon.png
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - toc.follow
    - navigation.top
    - content.code.copy
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: deep-orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: deep-orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode
markdown_extensions:
  - abbr:
  - tables:
  - toc:
  - admonition:
  - pymdownx.extra:
  - pymdownx.highlight:
      use_pygments: false
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js
  - javascripts/highlight.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/tokyo-night-dark.min.css
  - stylesheets/extra.css
extra:
  generator: false
  social:
    - icon: material/rabbit
      link: https://bunny.net?ref=pji59zr7a4
      name: Affiliate link
nav:
  - About: index.md
  - Getting Started: getting-started.md
  - API:
    - Base: base-api.md
    - Edge Storage: edge-storage-api.md
    - Stream: stream-api.md
    - Edge Scripting: edge-scripting-api.md
    - Logging: logging-api.md
  - Other:
    - Image Processing: image-processing.md
    - Token Authentication: token-authentication.md
