name: docs
on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup pages
        uses: actions/configure-pages@v6

      - name: Build docs
        run: docker run --rm -v $(pwd):/docs -w /docs docker.io/zensical/zensical:0.0 build --clean

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
