name: Generator
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

env:
  API_SPEC_MANIFEST: https://toshy.github.io/bunnynet-openapi-specification/manifest.json

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3

      - name: Run map generator
        run: php generator/Command/generate-maps.php

      - name: Run model generator
        run: php generator/Command/generate-models.php --log

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          commit-message: Updated API models
          title: '[OpenAPI] Updated API models'
          body: |
            Added/Updated models according to OpenAPI specs.

            Checklist:
            - [x] Add/Update API models
            - [ ] Add/Update API public methods for corresponding models
            - [ ] Update documentation
          branch: patch/models
          branch-suffix: short-commit-hash
          assignees: ToshY
          reviewers: ToshY
          labels: |
            OpenAPI
            automated
