name: PHPStan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  phpcs:
    name: PHPStan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions:
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3

      - name: PHPStan
        run: php vendor/bin/phpstan analyse --error-format=github --memory-limit=256M
